name: Build and Deploy CV
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          # Chỉ định đúng đường dẫn đến file main.tex trong thư mục src
          root_file: src/main.tex
          # Dùng xelatex để hỗ trợ tốt nhất cho font và ảnh
          compiler: xelatex
          # Cho phép cài đặt thêm các gói lệnh còn thiếu tự động
          latexmk_use_xelatex: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CV-Professional
          path: src/main.pdf