name: Build and Deploy CV
on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: src/main.tex
          compiler: xelatex 
         

      - name: Commit and Push PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/main.pdf
          git commit -m "Update compiled CV PDF" || echo "No changes to commit"
          git push